# Generated by savvy: do not edit by hand

#' @useDynLib od2net, .registration = TRUE
#' @importFrom tibble as_tibble
#' @keywords internal
NULL

#' Run od2net on origin/destination coordinate pairs
#'
#' @param osm_pbf_path Path to an input `.osm.pbf` file.
#' @param origin_lon,origin_lat Numeric vectors of origin coordinates.
#' @param dest_lon,dest_lat Numeric vectors of destination coordinates.
#' @param as_tibble Logical; return a tibble when `TRUE`, otherwise a list of columns.
#' @return Per-edge counts with columns `from_node`, `to_node`, `count`, `length_m`, and `lts`.
#' @export
od2net_counts <- function(osm_pbf_path,
                          origin_lon,
                          origin_lat,
                          dest_lon,
                          dest_lat,
                          as_tibble = TRUE) {
  stopifnot(length(origin_lon) == length(origin_lat),
            length(dest_lon) == length(dest_lat))

  result <- .Call(
    savvy_run_od2net_counts__impl,
    as.character(osm_pbf_path),
    as.numeric(origin_lon),
    as.numeric(origin_lat),
    as.numeric(dest_lon),
    as.numeric(dest_lat)
  )

  if (isTRUE(as_tibble)) {
    tibble::as_tibble(result)
  } else {
    result
  }
}

